### ISSUE TITLE
Clarify that session-definition contribution is distinct from scheming contribution

### ISSUE THREAD

**Issue by pes10k** [mikewest/scheming-cookies#1]
The proposal does two things that could be implemented independent of each other (session-def and behavior, scheming).

On my read of the document, I understood the proposal to be that we should scheme cookies first, and then once thats done, we can tighten up session stuff. (part of that is b/c of the title of the proposal)

Unless the above seems way off base to you / user error, I think the proposal would be stronger if it was clearer that the suggestions are independent, and not necessarily tied to each other.

**Comment by mikewest** [comment]
I added some text, which hopefully clarifies the intent. Ideally, I'll get around to folding this into the relevant spec (probably via https://mikewest.github.io/cookie-incrementalism/draft-west-cookie-incrementalism.html), which will also make things more concrete.

**Comment by pes10k** [comment]
thanks @mikewest ! I think tbh what threw me is the proposal being titled scheming cookies, which made me read it with a "this is a package deal" eye.  Thanks for the changes.

FWIW, Brave is planning on doing something similar (we've already started tying other privacy related behaviors to last-document length), so its valuable to know where ya'll are heading too.  Thanks!
