### ISSUE TITLE
Potential issues with Blob URL

### ISSUE THREAD

**Issue by shhnjk** [mikewest/scheming-cookies#2]
>cookies are given an internal scheme component, which retains the value of the scheme from which the cookie was set. If https://secure.example/ sends Set-Cookie: a=b, that cookie will store "https" as its scheme component. Likewise, http://nonsecure.example/ would store "http", and weird-scheme://weird.example would store "weird-scheme".

This suggests that if Blob URL (e.g. `blob:https://wwww.google.com`) sets cookie via `document.cookie`, the cookie will have `blob` as a scheme, and the cookie won't be shared with `https://wwww.google.com`? Isn't it a breaking change?

**Comment by mikewest** [comment]
1. We should get rid of `document.cookie`. Too bad it's used on +75% of page views ([get](https://chromestatus.com/metrics/feature/timeline/popularity/2195
) / [set](https://chromestatus.com/metrics/feature/timeline/popularity/2194)).

2. The origin of a blob URL (as well as documents loaded through that URL) is the origin represented by the inner bit (https://url.spec.whatwg.org/#concept-url-origin). That's what we use when calculating the "site for cookies" upon which a given operation works (see https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-05#section-5.2.1). The explainer is shortcutting this detail, but when I get around to speccing this, I'll make it clear that we ought to be looking at the origin's scheme, not the URL's scheme.

**Comment by shhnjk** [comment]
Sounds good :)

**Comment by mikewest** [comment]
I made sure this was included in the larger change at https://github.com/mikewest/cookie-incrementalism/commit/02c20c664f3bd0bff4f5e0e1b3e703d35ba98600, which is rendered at https://mikewest.github.io/cookie-incrementalism/draft-west-cookie-incrementalism.html#rfc.section.3.4.

Should eventually be available at https://tools.ietf.org/html/draft-west-cookie-incrementalism-01#section-3.4 as well.
